calicoSubnetSize: 22
cniConfigDir: /some/cni/conf/dir
cniPluginDir: /some/cni/bin/dir
cpuModel: host-model
criSocketPath: /some/cri.sock
databasePath: /some/file.db
disableKVM: true
disableLogging: true
downloadProtocol: http
enableRegexpImageTranslation: false
enableSriov: true
fdServerSocketPath: /some/fd/server.sock
imageDir: /var/lib/virtlet/images
imageTranslationConfigsDir: /some/translation/dir
libvirtURI: qemu:///foobar
logLevel: 3
rawDevices: sd*
skipImageTranslation: false
