apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: image-server
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        role: image-server
      annotations:
        pod.beta.kubernetes.io/init-containers: >
          [
            {
              "name": "dl-image",
              "image": "alpine:3.5",
              "imagePullPolicy": "IfNotPresent",
              "command": ["/bin/sh", "-c", "apk update && apk add ca-certificates wget && wget -O /images/cirros https://github.com/eprasad/virt-cirros/raw/master/virt-cirros-0.3.4-x86_64-disk.img"],
              "volumeMounts": [
                {
                  "name": "images",
                  "mountPath": "/images"
                }
              ]
            }
          ]
    spec:
      containers:
      - name: web
        image: nginx
        ports:
        - name: web
          containerPort: 80
        volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: images
      volumes:
      - name: images
        emptyDir: {}
